config/routes.rb
Rails.application.routes.draw do

 
  ActiveAdmin.routes(self)
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :flats
 # get 'groupages/form_opening'
       
  get 'containers/earnings_calculator'
  post 'containers/earnings_calculator'

  get 'pages/quotes_form_confirmation'
  get 'pages/partner_form_confirmation'
  get 'containers/form_opening'
  get 'pages/login'
  get 'pages/hire_mover'
  get 'pages/list_confirmation'
  get 'pages/search_container'
  get 'groupages/search_container'
  get 'pages/alert_confirmation'
  get 'terms_and_conditions', to: 'pages#terms_and_conditions', as: 'terms_and_conditions'
  get 'privacy_policy',       to: 'pages#privacy_policy', as: 'privacy_policy'
  get 'moving_guides',       to: 'pages#moving_guides', as: 'moving_guides'
  get 'share_my_container',       to: 'pages#share_my_container', as: 'share_my_container'
  
  # post 'calculator' => 'containers#calculator'
 
 #  resources :groupages, only: [:index, :show, :new, :create]
	# resources :containers, only: [:new, :create]
	 match "calculator" => "containers#calculator", :via => [:post, :get]
  root to: 'pages#home'

  resources :containers  do
    resources :groupages, only: [ :new, :create ]
  end

  resources :groupages, only: [:index, :show]
  resources :alerts, only: [:new, :create]
  resources :movers, only: [:index, :new, :create]
   resources :estimates
  resources :user_steps
  resources :lists, only: [ :new, :create, :edit, :update ]
  # root to: "savings#new"
  # match "calculator" => "pages#calculator", :via => [:post, :get]
  # post 'pages/home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/views/shared/_analytics.html.erb
<%= render '/shared/analytics/ga' %>
<%= render '/shared/analytics/fb_pixel' %>

app/views/shared/_favicon.html.erb
<%= favicon_link_tag 'apple-touch-icon.png', rel: 'apple-touch-icon', type: 'image/png' %>
<%= favicon_link_tag 'android-chrome-192x192.png', rel: 'icon', type: 'image/png' %>
<%= favicon_link_tag  %>
<%= favicon_link_tag 'safari-pinned-tab.svg', rel: 'mask-icon', color: '#5bbad5' %>

app/views/shared/_footer.html.erb
<footer class="footer-v2">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-6">
				<div class="logo-section">
					<%= link_to root_path, class: "logo-footer" do %>
						<%= image_tag "logo-footer.png", height: 30 %>
	   			 	<% end %>
	   		 		<p>coshippers is a community based relocation solution, making use of spare capacity and the power of community to solve the challenges of international moving.</p>
				</div>
			</div>
			<div class="col-xs-12 col-sm-3">
				<div class="footer-links">
					<h3>EXPLORE</h3>

					<p><%= link_to "Browse containers",  root_path %></p>
					<p><%= link_to "Start container : I need a container",   share_my_container_path  %></p> 
					<p><%= link_to "Start container : I have a container",   new_container_path  %></p>

					<p><%= link_to "Join as a moving company",  new_mover_path %></p> 
				</div>
				
			</div>
			<div class="col-xs-12 col-sm-3">
				<div class="contact-footer">
					<h3>CONTACT</h3>
					<div class="social-networks">
						<%= link_to "https://www.facebook.com/coshippers/" do %>
							<i class="fab fa-facebook-f"></i>
						<% end %>
						<%= link_to "#" do %>
							<i class="fab fa-twitter"></i>
						<% end %>
						<%= link_to "#" do %>
							<i class="fas fa-envelope"></i>
						<% end %>
					</div>
					<p>hello@coshippers.com</p>
				</div>
				 
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12">
				<hr>
				<div class="rights-reserved2">
					<p>© coshippers 2019 -  All rights reserved</p>
					<p><span class="color-tourquoise"><%= link_to "Terms and conditions ",  terms_and_conditions_path %>&nbsp; . &nbsp; <%= link_to "  Privacy Policy",   privacy_policy_path %></span> </p>
					
				</div>
			</div>
		</div>
	</div>
</footer>

















<!-- <footer class="footer">
	<div class="container">
		<div class="footer-line">
			<hr>
		</div>
		<div class="rights-reserved">
			<%#= link_to root_path, class: "logo-footer hidden-xs" do %>
	      		<%#= image_tag "logo-col-3x.png", height: 30 %>
	   		 <%# end %>
	   		<p>© coshippers 2019 -  All rights reserved
			</p>
		</div>
	</div>
</footer> -->

app/views/shared/_navbar-calculator-page.html.erb
<div class="navbar-wagon navbar-fixed-top hidden-xs">
  <!-- Logo -->
  <div class="logo">
    <%= link_to root_path do %>
      <%= image_tag "balloons@3x.png", height: 50, class: "mongolfier_logo" %>
    <% end %>
      <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo-col-3x.png", height: 50 %>
    <% end %>
    <%#= link_to "Find a mover", pages_hire_mover_path, class: "btn-nav-search-container" %>
  </div>


  

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>
      <% if params[:commit] %>
        <span class="earn-up-to navbar-wagon-item">Potential earnings </span>
        <button type="button" class="btn btn-information" data-toggle="modal" data-target="#estimate">
          <i class="fas fa-info-circle"></i>
        </button>
        <span class="savings-amount navbar-wagon-item"><%= number_with_precision(@result, :precision => 0, ) %></span><span class="currency navbar-wagon-item"><%= @currency %>
        </span>
      <% end %>

        <%= link_to "Browse containers", root_path , class: "navbar-wagon-item navbar-wagon-link btn-find-space" %>
           <!--  navbar link with dropdown menu -->
          <div class="navbar-wagon-item">
            <div class="dropdown">
              <div class="dropdown-toggle btn-offer-space navbar-wagon-link" data-toggle="dropdown">
                Start a container
              </div>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu navbar-dropdown-menu-right">
          
                <li><%= link_to share_my_container_path, class: "text-bold" do %>
                      I need a container
                      <p>Get free quotes from our preferred moving companies.</p>
                    <% end %>
                </li>
                <hr>
                <li><%= link_to new_container_path, class: "text-bold"  do %>
                      I have a container
                      <p>Find out how much you could 
                      earn renting your extra space.</p>
                    <% end %>
                </li>
                <hr>
                <li><%= link_to "Join as a moving company",   new_mover_path, class: "dark-grey-color" %></li>
              </ul>
            </div>
          </div>
      

            <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || "avatar-icon.png" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <%#= image_tag "avatar-icon.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu dropdown-menu-right-zero dark-grey-color">
          <!--   <li>
              <%#= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <%# end %>
            </li>
            <li>
              <%#= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <%# end %>
            </li> -->
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
        <!-- Login link (when logged out) -->
        <%= link_to "Browse containers", root_path , class: "navbar-wagon-item navbar-wagon-link btn-find-space" %>
       <div class="navbar-wagon-item">
           <div class="dropdown">
              <div class="dropdown-toggle btn-offer-space navbar-wagon-link" data-toggle="dropdown">
                Start a container
              </div>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu navbar-dropdown-menu-right">
          
                <li><%= link_to share_my_container_path, class: "text-bold" do %>
                      I need a container
                      <p>Get free quotes from our preferred moving companies.</p>
                    <% end %>
                </li>
                <hr>
                <li><%= link_to new_container_path, class: "text-bold"  do %>
                      I have a container
                      <p>Find out how much you could 
                      earn renting your extra space.</p>
                    <% end %>
                </li>
                <hr>
                <li><%= link_to "Join as a moving company",   new_mover_path, class: "dark-grey-color" %></li>
              </ul>
            </div>
      </div>
      
       <%= link_to "Sign up",  pages_login_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <%= link_to t(".sign_in", default: "Log in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Home",  root_path %></li>
          <hr>
          <li><%= link_to "Hire a mover",   pages_hire_mover_path %></li>
          <li><%= link_to "Learn about sharing my container",  new_container_path %></li>
           <li><%= link_to "Share my container",   share_my_container_path %></li>
           <li><%= link_to "Find a container",  pages_search_container_path %></li>
      </ul>
    </div>
  </div>
</div>


<!-- mobile navbar -->
<div class="navbar-mobile hidden-sm hidden-md hidden-lg">
   <div class="navbar-wagon-mobile ">
    <!-- Logo -->
   
    

    <!-- Right Navigation -->
   
        <!-- Links when logged in -->
       
        <!-- Avatar with dropdown menu -->
   

    <!-- Dropdown list appearing on mobile only -->
    <div class="hidden-md hidden-lg">
      <div class="dropdown">
        <!-- <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i> -->
        
          <div class="dropdown-toggle" data-toggle="dropdown">
          <%= image_tag "balloons@3x.png", height: 50, class: "mongolfier_logo" %>
          <%= image_tag "arrow.svg", height: 10, class: "arrow" %>
        </div>
        <%= link_to "list my container", containers_form_opening_path, class: "btn-nav-list-container" %>
        <%#= link_to "List my container", containers_form_opening_path, class: "btn-list-my-container navbar-wagon-item" %>
       
        
        
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Home",  root_path %></li>
          <hr>
          <li><%= link_to "Browse containers",  root_path, class: "search-icon-link" %></li>
          <hr>
          <span class="nav-title add-icon-link">Start a container</span>
          <li><%#= link_to "I need a container", share_my_container_path, class: "nav-subtitle" %></li>
          <li><%= link_to share_my_container_path, class: "nav-subtitle" do %>
              I need a container
                <p>Get free quotes from our 
                preferred moving companies.</p>
              <% end %>
          </li>
          <li><%= link_to new_container_path, class: "nav-subtitle subtitle-margin-top" do %>
              I have a container
              <p>Find out how much you could 
            earn renting your extra space.</p>
              <% end %>
          </li>
          <hr>
          <li><%= link_to "Join as a moving company",  new_mover_path %></li>
          <hr>
          <% if user_signed_in? %>
            <li><%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %></li> 
          <% else %>
            <li><%= link_to "Sign up",  pages_login_path, class: "navbar-wagon-item navbar-wagon-link" %></li> 
            <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li> 
          <% end %>


        </ul>


        </ul>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
  
<div class="navbar-wagon navbar-fixed-top hidden-xs">
  <!-- Logo -->
  <div class="logo">
    <%= link_to root_path do %>
      <%= image_tag "balloons@3x.png", height: 50, class: "mongolfier_logo" %>
    <% end %>
      <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo-col-3x.png", height: 50 %>
    <% end %>
    <%#= link_to "Find a mover", pages_hire_mover_path, class: "btn-nav-search-container" %>
  </div>

  

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>
   
    
      
  

      <!-- Links when logged in -->
      <%#= link_to "List my container", new_container_path , class: "navbar-wagon-item navbar-wagon-link" %>
         <!-- <i class="fas fa-people-carry"></i><%#= link_to "Hire a mover",pages_hire_mover_path , class: "navbar-wagon-item navbar-wagon-link btn-hire-mover" %> -->
      <%= link_to "Browse containers", pages_search_container_path , class: "navbar-wagon-item navbar-wagon-link btn-find-space" %>
  
        <!--  navbar link with dropdown menu -->
        <div class="navbar-wagon-item">
         <div class="dropdown">
              <div class="dropdown-toggle btn-offer-space navbar-wagon-link" data-toggle="dropdown">
                Start a container
              </div>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu navbar-dropdown-menu-right">
          
                <li><%= link_to share_my_container_path, class: "text-bold" do %>
                      I need a container
                      <p>Get free quotes from our preferred moving companies.</p>
                    <% end %>
                </li>
                <hr>
                <li><%= link_to new_container_path, class: "text-bold"  do %>
                      I have a container
                      <p>Find out how much you could 
                      earn renting your extra space.</p>
                    <% end %>
                </li>
                <hr>
                <li><%= link_to "Join as a moving company",   new_mover_path, class: "dark-grey-color" %></li>
              </ul>
            </div>
      </div>











      

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || "avatar-icon.png" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <%#= image_tag "avatar-icon.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu dropdown-menu-right-zero dark-grey-color">
          <!--   <li>
              <%#= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <%# end %>
            </li>
            <li>
              <%#= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <%# end %>
            </li> -->
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "Browse containers", pages_search_container_path , class: "navbar-wagon-item navbar-wagon-link btn-find-space" %>
       <div class="navbar-wagon-item">
           <div class="dropdown">
              <div class="dropdown-toggle btn-offer-space navbar-wagon-link" data-toggle="dropdown">
                Start a container
              </div>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu navbar-dropdown-menu-right">
          
                <li><%= link_to share_my_container_path, class: "text-bold" do %>
                      I need a container
                      <p>Get free quotes from our preferred moving companies.</p>
                    <% end %>
                </li>
                <hr>
                <li><%= link_to new_container_path, class: "text-bold"  do %>
                      I have a container
                      <p>Find out how much you could 
                      earn renting your extra space.</p>
                    <% end %>
                </li>
                <hr>
                <li><%= link_to "Join as a moving company",   new_mover_path, class: "dark-grey-color" %></li>
              </ul>
            </div>
      </div>
      
       <%= link_to "Sign up",  pages_login_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <%= link_to t(".sign_in", default: "Log in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Home",  root_path %></li>
          <hr>
          <li><%= link_to "Hire a mover",   pages_hire_mover_path %></li>
          <li><%= link_to "Learn about sharing my container",  new_container_path %></li>
           <li><%= link_to "Share my container",   share_my_container_path %></li>
           <li><%= link_to "Find a container",  pages_search_container_path %></li>
      </ul>
    </div>
  </div>
</div>


<!-- mobile navbar -->
<div class="navbar-mobile hidden-sm hidden-md hidden-lg">
   <div class="navbar-wagon-mobile ">
    <!-- Logo -->
   
    

    <!-- Right Navigation -->
   
        <!-- Links when logged in -->
       
        <!-- Avatar with dropdown menu -->
   

    <!-- Dropdown list appearing on mobile only -->
    <div class="hidden-md hidden-lg">
      <div class="dropdown">
        <!-- <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i> -->
        
          <div class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag "balloons@3x.png", height: 50, class: "mongolfier_logo" %>
            <%= image_tag "arrow.svg", height: 10, class: "arrow" %>
          </div>
          <%= link_to "Search containers", pages_search_container_path, class: "btn-nav-get-quotes smaller-padding" %>


       
        
        
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Home",  root_path %></li>
          <hr>
          <li><%= link_to "Browse containers",  pages_search_container_path, class: "search-icon-link" %></li>
          <hr>
          <span class="nav-title add-icon-link">Start a container</span>
          <li><%#= link_to "I need a container", share_my_container_path, class: "nav-subtitle" %></li>
          <li><%= link_to share_my_container_path, class: "nav-subtitle" do %>
              I need a container
                <p>Get free quotes from our 
                preferred moving companies.</p>
              <% end %>
          </li>
          <li><%= link_to new_container_path, class: "nav-subtitle subtitle-margin-top" do %>
              I have a container
              <p>Find out how much you could 
            earn renting your extra space.</p>
              <% end %>
          </li>
          <hr>
          <li><%= link_to "Join as a moving company",  new_mover_path %></li>
          <hr>
          <% if user_signed_in? %>
            <li><%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %></li> 
          <% else %>
            <li><%= link_to "Sign up",  pages_login_path, class: "navbar-wagon-item navbar-wagon-link" %></li> 
            <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li> 
          <% end %>


        </ul>
      </div>
    </div>
  </div>
</div>

</div>

app/views/shared/_navbar_mover.html.erb
<div class="navbar-wagon navbar-fixed-top hidden-xs">
  <!-- Logo -->
  <div class="logo">
    <%= link_to root_path do %>
      <%= image_tag "balloons@3x.png", height: 50, class: "mongolfier_logo" %>
    <% end %>
      <%= link_to root_path, class: "navbar-wagon-brand" do %>
      <%= image_tag "logo-col-3x.png", height: 50 %>
    <% end %>
    <%#= link_to "Find a mover", pages_hire_mover_path, class: "btn-nav-search-container" %>
  </div>

  

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>
   
    
      
  

      <!-- Links when logged in -->
      
      <%= link_to "Browse containers", root_path , class: "navbar-wagon-item navbar-wagon-link btn-find-space" %>
      <div class="navbar-wagon-item">
            <div class="dropdown">
              <div class="dropdown-toggle btn-offer-space navbar-wagon-link" data-toggle="dropdown">
                Start a container
              </div>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu navbar-dropdown-menu-right">
                <li><%= link_to share_my_container_path, class: "text-bold" do %>
                      I need a container
                      <p>Get free quotes from our preferred moving companies.</p>
                    <% end %>
                </li>
                <hr>
                <li><%= link_to new_container_path, class: "text-bold"  do %>
                      I have a container
                      <p>Find out how much you could 
                      earn renting your extra space.</p>
                    <% end %>
                </li>
                <hr>
                <li><%= link_to "Join as a moving company",   new_mover_path, class: "dark-grey-color" %></li>
              </ul>
            </div>
          </div>
      

      <!-- Avatar with dropdown menu -->
           <div class="navbar-wagon-item">
        <div class="dropdown">
          <% avatar_url = current_user.facebook_picture_url || "avatar-icon.png" %>
          <%= image_tag avatar_url, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>

          <%#= image_tag "avatar-icon.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu dropdown-menu-right-zero dark-grey-color">
          <!--   <li>
              <%#= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <%# end %>
            </li>
            <li>
              <%#= link_to "#" do %>
                <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <%# end %>
            </li> -->
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to "Browse containers", root_path , class: "navbar-wagon-item navbar-wagon-link btn-find-space" %>
      <div class="navbar-wagon-item">
            <div class="dropdown">
              <div class="dropdown-toggle btn-offer-space navbar-wagon-link" data-toggle="dropdown">
                Start a container
              </div>
              <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu navbar-dropdown-menu-right">
          
                <li><%= link_to share_my_container_path, class: "text-bold" do %>
                      I need a container
                      <p>Get free quotes from our preferred moving companies.</p>
                    <% end %>
                </li>
                <hr>
                <li><%= link_to new_container_path, class: "text-bold"  do %>
                      I have a container
                      <p>Find out how much you could 
                      earn renting your extra space.</p>
                    <% end %>
                </li>
                <hr>
                <li><%= link_to "Join as a moving company",   new_mover_path, class: "dark-grey-color" %></li>
              </ul>
            </div>
          </div>
       <%= link_to "Sign up",  pages_login_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <%= link_to t(".sign_in", default: "Log in"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "Home",  root_path %></li>
          <hr>
          <li><%= link_to "Hire a mover",   pages_hire_mover_path %></li>
          <li><%= link_to "Learn about sharing my container",  new_container_path %></li>
           <li><%= link_to "Share my container",   share_my_container_path %></li>
           <li><%= link_to "Find a container",  pages_search_container_path %></li>
      </ul>
    </div>
  </div>
</div>


<!-- mobile navbar -->
<div class="navbar-mobile hidden-sm hidden-md hidden-lg">
   <div class="navbar-wagon-mobile ">
    <!-- Logo -->
   
    

    <!-- Right Navigation -->
   
        <!-- Links when logged in -->
       
        <!-- Avatar with dropdown menu -->
   

    <!-- Dropdown list appearing on mobile only -->
    <div class="hidden-md hidden-lg">
      <div class="dropdown">
        <!-- <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i> -->
        
          <div class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag "balloons@3x.png", height: 50, class: "mongolfier_logo" %>
            <%= image_tag "arrow.svg", height: 10, class: "arrow" %>
          </div>
          <%= link_to "List my company", new_mover_path(anchor: 'partner_form'), class: "btn-nav-list-company" %>
       
        
        
         <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to "Home",  root_path %></li>
          <hr>
          <li><%= link_to "Browse containers",  root_path, class: "search-icon-link" %></li>
          <hr>
          <span class="nav-title add-icon-link">Start a container</span>
          <li><%= link_to share_my_container_path, class: "nav-subtitle" do %>
                I need a container
                <p>Get free quotes from our 
                preferred moving companies.</p>
              <% end %>
          </li>
          <li><%= link_to new_container_path, class: "nav-subtitle subtitle-margin-top" do %>
                I have a container
                <p>Find out how much you could 
            earn renting your extra space.</p>
            <% end %>
          </li>
          <hr>
          <li><%= link_to "Join as a moving company",  new_mover_path %></li>
          <hr>
          <% if user_signed_in? %>
            <li><%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
                <% end %></li> 
          <% else %>
            <li><%= link_to "Sign up",  pages_login_path, class: "navbar-wagon-item navbar-wagon-link" %></li> 
            <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li> 
          <% end %>


        </ul>
      </div>
    </div>
  </div>
</div>

</div>