config/routes.rb
Rails.application.routes.draw do

 
  ActiveAdmin.routes(self)
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :flats
 # get 'groupages/form_opening'
       
  get 'containers/earnings_calculator'
  post 'containers/earnings_calculator'

  get 'pages/quotes_form_confirmation'
  get 'pages/partner_form_confirmation'
  get 'containers/form_opening'
  get 'pages/login'
  get 'pages/hire_mover'
  get 'pages/list_confirmation'
  get 'pages/search_container'
  get 'groupages/search_container'
  get 'pages/alert_confirmation'
  get 'terms_and_conditions', to: 'pages#terms_and_conditions', as: 'terms_and_conditions'
  get 'privacy_policy',       to: 'pages#privacy_policy', as: 'privacy_policy'
  get 'moving_guides',       to: 'pages#moving_guides', as: 'moving_guides'
  get 'share_my_container',       to: 'pages#share_my_container', as: 'share_my_container'
  
  # post 'calculator' => 'containers#calculator'
 
 #  resources :groupages, only: [:index, :show, :new, :create]
	# resources :containers, only: [:new, :create]
	 match "calculator" => "containers#calculator", :via => [:post, :get]
  root to: 'pages#home'

  resources :containers  do
    resources :groupages, only: [ :new, :create ]
  end

  resources :groupages, only: [:index, :show]
  resources :alerts, only: [:new, :create]
  resources :movers, only: [:index, :new, :create]
   resources :estimates
  resources :user_steps
  resources :lists, only: [ :new, :create, :edit, :update ]
  # root to: "savings#new"
  # match "calculator" => "pages#calculator", :via => [:post, :get]
  # post 'pages/home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/container.rb
class Container < ApplicationRecord
	has_one :groupage
	belongs_to :user

	validates :container_size, :volume, :metrics, :price, :currency,  presence: true, on: :update

	# validates :container_size, :volume, :metrics, :price, :currency,  presence: true, if: :should_validate?


	CONTAINERS = [ ["20" , 30], ["40", 60]]
				# 20 means 20'(feet) container
				# 40 means 40'(feet) container

	# validates :container_size, inclusion: {in: CONTAINERS}

	METRIC = [
				["m3 - cubic meters", 1],
				["cuft - cubic feet", 35,3147]
			]
	# validates :metrics, inclusion: {in: METRIC}

	CURRENCIES = ["EUR", "USD", "GBP", "CHF", "***", "AUD", "BRL", "CAD", "CHF",
								"CLP", "CNY", "CZK", "DKK", "HKD", "HUF", "IDR", "ILS", "INR",
								"JPY", "KRW", "MXN", "MYR", "NOK", "NZD", "PHP", "PKR", "PLN" , 
								"RUB", "SEK", "SGD", "THB", "TRY", "TWD", "ZAR"
								]
	# validates :currency, inclusion: {in: CURRENCIES}

	def should_validate?
    	new_record? || volume.present?

  	end


end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
skip_before_action :authenticate_user!, only: [:new, :calculator, :earnings_calculator, :form_opening, :update]

  layout "calculator"


  def calculator
    @container = Container.new
  	@container = Container.new(container_params)
  	@metrics = @container[:metrics].to_f
  	@container_size = @container[:container_size].to_f * @metrics
  	@volume = @container[:volume].to_f
  	@price = @container[:price].to_f
 	  @currency = @container[:currency]
    @left_space = @container_size - @volume 

    @result = (@price / @container_size) * @left_space
  end

  def earnings_calculator
    @estimate = Estimate.new
    @container = Container.new
    @container = Container.new(container_params)
    @metrics = @container[:metrics].to_f
    # @container_size = @container[:container_size].to_f * @metrics
    @volume = @container[:volume].to_f
    @price = @container[:price].to_f
    @currency = @container[:currency]
    


   # Container::CONTAINERS = [
   #        ["20’ container", 30],
   #        ["40’ container", 60]
          
   #      ]

    @container_size = 0

    if  @metrics == 1
      if @volume <= 27
        container_size = Container::CONTAINERS[0][1]
        @container_size = Container::CONTAINERS[0][0] 
        @metrics_display = "M3"

      elsif @volume > 27 &&  @volume < 58
        container_size = Container::CONTAINERS[1][1]
        @container_size = Container::CONTAINERS[1][0]
         @metrics_display = "M3"

      else
          container_size = Container::CONTAINERS[1][1]
          @container_size = Container::CONTAINERS[1][0]
          @metrics_display = "M3"
          # redirect_to containers_earnings_calculator_path, notice: "Great! We'll get in touch with you soon."
         flash[:notice]='Your move is too big to share a container.'
         
      end 
    elsif @metrics == 35

      if @volume <= 950
        container_size = Container::CONTAINERS[0][1]
        @container_size = Container::CONTAINERS[0][0] 
         @metrics_display = "CUFT"
      elsif @volume > 950 &&  @volume < 2000
        container_size = Container::CONTAINERS[1][1]
        @container_size = Container::CONTAINERS[1][0]
        @metrics_display = "CUFT"
      else
        container_size = Container::CONTAINERS[1][1]
        @container_size = Container::CONTAINERS[1][0]
        @metrics_display = "CUFT"
         flash[:notice]='Your move is too big to share a container.'
        
      end 
      
    end 
      container = container_size* @metrics
      @left_space = container - @volume 
      @result = (@price / container) * @left_space

    

    
  end

  def form_opening

    @container = Container.new
    @groupage = Groupage.new
    # @container = Container.new(params[:container])
    
    # @container = Container.find(@container.id)
    render layout: "form-cover"
  end
  def new
    @container = Container.new
  end

  def create
  #   @container = Container.new
  #   @container = Container.new(container_params)
  #   @groupage = Groupage.find(@groupage.id)
  #   @groupage.container = @container
  #    @container.user = current_user
  #     if @container.save
  #       redirect_to user_steps_path
  #     else
  #       render :new
  #     end
  end

  def edit
    @container = Container.find(params[:id])
    render layout: "groupage-form"
    
  end

  def update
    @container = Container.find(params[:id])
    @container.update(container_params)
    if @container.save
      redirect_to user_steps_path
    else
      render :edit
    end

    # @groupage = Groupage.new(params[:groupage])
    # @groupage = Groupage.find(@groupage.id)
    # @container = @groupage.container
    # @container = Container.new(params[:container])

  end

  private 

  def container_params
  	params.require(:container).permit(:container_size, :volume, :price, :metrics, :currency)
  end

  def resolve_layout
    case actio_name
    when "calculator" 
      "calculator"
    when "form_opening"
      "calculator"
    else
      "application"
    end
  end

end

app/views/containers/_calculator-form-dskt.html.erb
<div class="form-calculator">
	<h1>Share your container <br>and earn money</h1>
	<p>Find out how much your unused space is worth</p>
	<%#= form_for  root_path, :method => "POST" do %>
 	<%= simple_form_for @container, url: calculator_path do |f| %>

	
		<div class="row">
			<div class="col-xs-12">
	
				<%= f.input :container_size, label: false, collection: Container::CONTAINERS, prompt: "My container size" %>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-7">
				<%= f.input :volume, as: :integer, label: false, input_html: { class: 'large-input' }, placeholder: "Volume of my move" %>
			</div>
			<div class="col-xs-5">
				<%= f.input :metrics, label: false,input_html: { class: 'special' }, collection: Container::METRIC, prompt: params[:metrics] %>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-7">
				<%= f.input :price, as: :integer, label: false, input_html: { class: 'large-input' },  placeholder: "Best price you got so far" %>
			</div>
			<div class="col-xs-5">
				<%= f.input :currency, label: false, input_html: { class: 'special' },  collection: Container::CURRENCIES, prompt: params[:currency]%>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-7 results-section">

				<% if params[:commit]%>
					<div class="results-values">
						<h3> <span class="results-savings"><%= number_with_precision(@result, :precision => 0, ) %></span> <span class="results-currency"><%= @currency %></span></h3>
						 <span class="results-earn-up-to ">Potential earnings</span>
						 <button type="button" class="btn btn-information" data-toggle="modal" data-target="#estimate">
							  <i class="fas fa-info-circle"></i>
						</button>
					</div>
				<% end %>
			</div>
			<div class="col-xs-5">
				<div class="results-btn">
					<%= f.submit "Calculate", class: "btn btn-calculate"  %>
				</div>
			</div>
		</div>
	<%	end  %>
	 <%= render 'containers/modal_information' %>
</div>

app/views/containers/_calculator-form-mobile.html.erb
<div class="mob-form-calculator">
	<p>Find out how much your unused <br>space is worth</p>
	<%= simple_form_for @container, url: calculator_path do |f| %>
		<div class="row">
			<div class="col-xs-12">
	
				<%= f.input :container_size, label: false, collection: Container::CONTAINERS, prompt: "My container size" %>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-7">
				<%= f.input :volume, as: :integer, label: false, input_html: { class: 'large-input' }, placeholder: "Volume of my move" %>
			</div>
			<div class="col-xs-5">
				<%= f.input :metrics, label: false,input_html: { class: 'special' }, collection: Container::METRIC, prompt: params[:metrics] %>
			</div>
		</div>
		<div class="row">
			<div class="col-xs-7">
				<%= f.input :price, as: :integer, label: false, input_html: { class: 'large-input' },  placeholder: "Best price you got so far" %>
			</div>
			<div class="col-xs-5">
				<%= f.input :currency, label: false, input_html: { class: 'special' },  collection: Container::CURRENCIES , prompt: params[:currency] %>
			</div>
		</div>
		<% if params[:commit] %>
			<div class="row">
				<div class="col-xs-12">
						<h3> <span class="results-savings"><%= number_with_precision(@result, :precision => 0, ) %></span> <span class="results-currency"><%= @currency %></span></h3>
				</div>
			</div>
			<div class="row">
				<div class="col-xs-12">
					<div class="information">
						<span class="results-earn-up-to">Potential earnings</span>
						 <button type="button" class="btn btn-information" data-toggle="modal" data-target="#estimate-mobile">
							  <i class="fas fa-info-circle"></i>
						</button>
					</div>
				</div>
			</div>
		<% end %>
		<div class="row">
			<div class="col-xs-12">
				<div class="results-btn">
					<%= f.submit "Calculate", class: "btn btn-calculate"  %>
				</div>
			</div>
		</div>
		</div>
	<% end %>
	<%= render 'containers/modal-information-mobile' %>
</div>

app/views/containers/_modal-information-mobile.html.erb
<!-- Modal -->
<div class="modal fade" id="estimate-mobile" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">How the calculator works</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>This earnings estimate assumes most of your unused space is booked (container is 91% full), and uses your own door to door price to calculate selling per cubic meter/ cubic feet. <br> <br>

        How much you actually make may vary with your container cost, dates of your move, itinerary of your move, actual occupancy rate, season, demand, local laws, and other factors. <br><br>

        __ <br>
        <b>Detailed calculations </b><br><br>

        <u><b>1- Price per m3 / cuft</b></u> <br>
        The calculator estimates a selling price per m3 / cuft using : <br>
        - the figure you provided under “best quote I got” <br>
        - your container size <br>
        - the maximum container occupancy. <br><br>

        Example: for a 20’ container quoted at 6,000 USD, we’ d suggest to sell every m3 of unused space at 200 USD maximum (or ~5.66 USD per cuft). <br>
        -> 6,000 USD / 33 m3 x 91% = ~200 USD/m3 <br><br>

        <u><b>2- Amount of space you can spare/make available for bookings</b></u><br>
        The calculator considers the amount of space you can spare using: <br>
        - your own move size <br>
        - your container size <br> 
        - a default maximum container occupancy of 91%. <br> <br>

        Example: if the volume of your move is 20 m3/700 cuft and you have booked a 20’ container, the calculator considers you have ~10 m3/350 cuft of unused space.
        -> 33 m3 x 91% - 20 m3 = ~10 m3 <br> <br>

        <u><b>3- Container sizes </b></u><br>
        20’ Container - approx. 33 m3 / 1,165 cuft <br>
        40’ Container - approx. 66 m3 / 2,330 cuft <br>
        40’ High cube - approx. 76 m3 / 2,684 cuft <br> <br>

        https://en.wikipedia.org/wiki/ Inte<br>rmodal_container#Specifications</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-estimate-modal-close" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/containers/_modal_information.html.erb
<!-- Modal -->
<div class="modal fade" id="estimate" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">How the calculator works</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>This earnings estimate assumes most of your unused space is booked (container is 91% full), and uses your own door to door price to calculate selling per cubic meter/ cubic feet. <br> <br>

        How much you actually make may vary with your container cost, dates of your move, itinerary of your move, actual occupancy rate, season, demand, local laws, and other factors. <br><br>

        __ <br>
        <b>Detailed calculations </b><br><br>

        <u><b>1- Price per m3 / cuft</b></u> <br>
        The calculator estimates a selling price per m3 / cuft using : <br>
        - the figure you provided under “best quote I got” <br>
        - your container size <br>
        - the maximum container occupancy. <br><br>

        Example: for a 20’ container quoted at 6,000 USD, we’ d suggest to sell every m3 of unused space at 200 USD maximum (or ~5.66 USD per cuft). <br>
        -> 6,000 USD / 33 m3 x 91% = ~200 USD/m3 <br><br>

        <u><b>2- Amount of space you can spare/make available for bookings</b></u><br>
        The calculator considers the amount of space you can spare using: <br>
        - your own move size <br>
        - your container size <br> 
        - a default maximum container occupancy of 91%. <br> <br>

        Example: if the volume of your move is 20 m3/700 cuft and you have booked a 20’ container, the calculator considers you have ~10 m3/350 cuft of unused space.
        -> 33 m3 x 91% - 20 m3 = ~10 m3 <br> <br>

        <u><b>3- Container sizes </b></u><br>
        20’ Container - approx. 33 m3 / 1,165 cuft <br>
        40’ Container - approx. 66 m3 / 2,330 cuft <br>
        40’ High cube - approx. 76 m3 / 2,684 cuft <br> <br>

        https://en.wikipedia.org/wiki/ Intermodal_container#S <br>pecifications</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-estimate-modal-close" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/containers/calculator.html.erb
<%= render 'homepage' %>

app/views/containers/earnings_calculator.html.erb
<%= render 'shared/share_my_container_calculator' %>

app/views/containers/edit.html.erb
<div class="full-container">
	<!-- container information -->
	<div class="progressbar">
		<div class="logo">
			<%= link_to  new_container_path, class: "navbar-wagon-brand" do %>
      			<%= image_tag "balloons@3x.png", height: 50, class: "ballon-logo" %>
    		<% end %>
    		<h2>Step 1 : Start with the basics </h2>
		</div>	
	</div>
	<div class="progress">
  		<div class="progress-bar background-tuorquoise" role="progressbar" style="width: 75%" aria-valuenow="75" aria-valuemin="0" aria-valuemax="100">
  			
  		</div>
	</div>

	<div class="container">
		<div class="row">
			<%= simple_form_for @container do |f| %>
			  	<%#  f.input :venue_id, :as => :hidden, :input_html => { :value => @venue.id } %>
				<div class="col-sm-6">
					<div class="itinerary-section form">
						<div class="row">
							<div class="col-xs-12 col-sm-12">
								<h3>What is the size of your container?</h3>
								<%= f.input :container_size, label: false, collection: Container::CONTAINERS, prompt: "My container size" %>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12">
								<h3>What is the volume of your move?</h3>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-7 col-sm-8">
								<%= f.input :volume, label: false, placeholder: "Enter your volume" %>
							</div>
							<div class="col-xs-5 col-sm-4">
								<%= f.input :metrics, label: false, collection: Container::METRIC, prompt: params[:metrics] %>
							</div>
						</div>	
						<div class="when-you-move">
							<div class="row">
								<div class="col-xs-12">
									<h3>How much are you paying for your move?</h3>
								</div>
							</div>
							<div class="row">
								<div class="col-xs-7 col-sm-8">
									<%= f.input :price, label: false, placeholder: "Enter amount here" %>

								</div>
								<div class="col-xs-5 col-sm-4">
									<%= f.input :currency, label: false,  collection: Container::CURRENCIES, prompt: params[:currency]%>
								</div>
							</div>
							<div class="row">
								<div class="col-xs-12 col-sm-12">
									<div class="container-info">
										<p>Note : Enter the amount excluding insurance & other accessorial costs then choose the currency. <br>
										Entering the price of your move helps us suggest selling prices for the space you don’t use.</p>
									</div>
									
								</div>
							</div>	
						
						</div>
					</div>
					<hr class="hidden-xs">
					<div class="row hidden-xs">
						<div class="btn-section">
							<div class="back-link">
								<%#= link_to 'Back', url_for(:back) %>
								<%= link_to url_for(:back) , class: "btn-back-link" do %>
										<i class="fas fa-chevron-left"></i>
									<% end %>
								<%= link_to "Back", url_for(:back), class: "btn-back-link" %>
								
							</div>
							<div class="next-button">
								<%= f.submit "Next", class: "btn btn-next"  %>
							</div>
						</div>
					</div>
						
				</div>
				<div class="col-xs-12 col-sm-6">
					<div class="flexbox">
						<div class="information-box">
							<%= image_tag "bulb.svg", height: 30, class: "lamp-icon" %>
							<p><%= (2..5).to_a.sample %> expats are moving on a similar itinerary and looking for space.</p>
						</div>
					</div>
				</div>
				<div class="hidden-sm hidden-md hidden-lg">
					<!-- <div class="col-xs-12"> -->
						<div class="action-buttons-section">
							<div class="back-link">
								<%#= link_to 'Back to this p', url_for(:back) %>
								<%= link_to containers_form_opening_path, class: "btn-back-link" do %>
										<i class="fas fa-chevron-left"></i>
									<% end %>
								<%= link_to "Back", containers_form_opening_path, class: "btn-back-link" %>
								
								
							</div>
							<div class="next-button">
								<%= f.submit "Next", class: "btn btn-next"  %>
							</div>
						</div>
					<!-- </div> -->
					
				</div>
			<% end %>
		</div>
	</div>

</div>

app/views/containers/form_opening.html.erb
<div class="opening-form-section">
	<!-- <div class="stiky-progressbar hidden-sm hidden-md hidden-lg">
		<div class="progressbar">
			<div class="logo">
				<%= link_to  new_container_path, class: "navbar-wagon-brand" do %>
	      			<%= image_tag "balloons@3x.png", height: 50, class: "ballon-logo" %>
	    		<% end %>
	    		<h2>List your container</h2>
			</div>	
		</div>
		<div class="progress">
	  		<div class="progress-bar background-tuorquoise" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
	  			
	  		</div>
		</div>
	</div> -->
	<div class="progressbar">
		
		<div class="logo">
			<%= link_to  new_container_path, class: "navbar-wagon-brand" do %>
      			<%= image_tag "balloons@3x.png", height: 50, class: "ballon-logo" %>
    		<% end %>
    		<h2>List your container</h2>
		</div>	
	</div>
	<div class="progress">
  		<div class="progress-bar background-tuorquoise" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">
  			
  		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-6">
				<h2>Before you continue.</h2>
				<p>Listing your container on coshippers is only possible if you have already booked your move/container with a trusted international moving company. <br>
				<br>
				If you have not booked your move yet, simply request
					<%= link_to "our list of trusted international moving companies", pages_hire_mover_path, class: "turquoise-color" %> in your country and start requesting quotes.</p>
				<div class="buttons-section">
					<%= link_to "Cancel", new_container_path, class: "btn-cancel" %>
					 <%= link_to "Continue",  new_container_groupage_path([:container_id]) , class: "btn-list-my-container" %>
				</div>			
			</div>		
				
			<div class="col-xs-12 col-sm-6 hidden-xs">
				<div class="image-background">
					<%= image_tag "ship.svg", height: 600, class: "ship-img" %>
				</div>
				
			</div>
		</div>
		
	</div>
	<!-- <div class="devise-mobile-footer ">
		<div class="mob-form-box hidden-sm hidden-md hidden-lg">
			<hr>
			<div class="rights-reserved">  
		    	<p>© mygroupage 2018 -  All rights reserved</p>
		    	<p>Terms of service  ·  Privacy Policy</p>
			</div>
		</div>
	</div> -->
</div>

app/views/containers/new.html.erb
<%= render 'homepage' %>