config/routes.rb
Rails.application.routes.draw do

 
  ActiveAdmin.routes(self)
  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :flats
 # get 'groupages/form_opening'
       
  get 'containers/earnings_calculator'
  post 'containers/earnings_calculator'

  get 'pages/quotes_form_confirmation'
  get 'pages/partner_form_confirmation'
  get 'containers/form_opening'
  get 'pages/login'
  get 'pages/hire_mover'
  get 'pages/list_confirmation'
  get 'pages/search_container'
  get 'groupages/search_container'
  get 'pages/alert_confirmation'
  get 'terms_and_conditions', to: 'pages#terms_and_conditions', as: 'terms_and_conditions'
  get 'privacy_policy',       to: 'pages#privacy_policy', as: 'privacy_policy'
  get 'moving_guides',       to: 'pages#moving_guides', as: 'moving_guides'
  get 'share_my_container',       to: 'pages#share_my_container', as: 'share_my_container'
  
  # post 'calculator' => 'containers#calculator'
 
 #  resources :groupages, only: [:index, :show, :new, :create]
	# resources :containers, only: [:new, :create]
	 match "calculator" => "containers#calculator", :via => [:post, :get]
  root to: 'pages#home'

  resources :containers  do
    resources :groupages, only: [ :new, :create ]
  end

  resources :groupages, only: [:index, :show]
  resources :alerts, only: [:new, :create]
  resources :movers, only: [:index, :new, :create]
   resources :estimates
  resources :user_steps
  resources :lists, only: [ :new, :create, :edit, :update ]
  # root to: "savings#new"
  # match "calculator" => "pages#calculator", :via => [:post, :get]
  # post 'pages/home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/groupage.rb
class Groupage < ApplicationRecord
  belongs_to :user
  belongs_to :container, dependent: :destroy
  # before_save :geocode_endpoints
  validates :departure_date, :origin, :destination, presence: true
  # validates :mover, presence: true, on: :mover_info
    # validates :mover, presence: true, on: :personal_info
  validates :departure_date, :origin, :destination, presence: true, on: :index



  geocoded_by :origin, :latitude => :latitude, :longitude => :longitude
  geocoded_by :destination, :latitude => :destination_latitude, :longitude => :destination_longitude
  after_validation :geocode_endpoints, if: :will_save_change_to_origin?
  after_validation :geocode_endpoints, if: :will_save_change_to_destination?


	PHONE_PREFIX = @currencies = ["+33", "+44", "+35", "+61", "+1"]
	# validates :phone_prefix, inclusion: {in: PHONE_PREFIX}

	def geocode_endpoints
	    if origin_changed?
	      geocoded = Geocoder.search(origin).first
	      if geocoded
	        self.latitude = geocoded.latitude
	        self.longitude = geocoded.longitude
	      end
	    end
	    if destination_changed?
	      geocoded = Geocoder.search(destination).first
	      if geocoded
	        self.destination_latitude = geocoded.latitude
	        self.destination_longitude = geocoded.longitude
	      end
	    end
	end
end

app/controllers/groupages_controller.rb
class GroupagesController < ApplicationController
	skip_before_action :authenticate_user!, only: [:index, :show]
  # before_action :set_container, only: [:create]
  
  
 
  def form_opening
  end

  

  def index
    @groupage = Groupage.new
    @params_hash = request.query_parameters[:groupage]
    @groupage = @params_hash

  end

  def show
  end

  def new
  	@groupage = Groupage.new
    @container = Container.new
    render layout: "groupage-form"
    
  end

  def create
    @container = Container.new(params[:container])
    @container.user = current_user
    @container.save
    @container = Container.find(@container.id)

    # @groupage = Groupage.new(groupage_params)
    # @groupage.container = @container

    # @user = User.new(params[:user])
    # @user.save
    # @user = current_user
    # @user = User.find(@user.id)
    # @groupage.user = current_user
    @groupage = Groupage.new(groupage_params)
    @groupage.container = @container

    @groupage.user = @groupage.container.user 

      if @groupage.save

        redirect_to edit_container_path(@container)
      else
        render :new
        # format.json { render json: @groupage.errors, status: :unprocessable_entity }

      end

  end


  private
    # def set_container
    #   @container = Container.find(params[:container_id])
    # end

  def groupage_params
    params.require(:groupage).permit(:origin, :destination, :departure_date, :mover, :notification_email, :phone_number, :phone_prefix)
  end




end

app/views/groupages/_groupage-form.html.erb
<div class="full-container">
	<!-- itenerary section -->
	<div class="container">
		<div class="row">
			<%= simple_form_for [@container, @groupage], :html => { :multipart => true }, :url => {:controller => 'groupages', :action => 'create'} do |f| %>
			<%#  f.input :container_id, :as => :hidden, :input_html => { :value => @container.id } %>
				<div class="col-sm-6">
					<div class="itinerary-section form">
						<div class="row">
							<div class="col-sm-12">
								<h3>What is your move’s itinerary?</h3>
								<%= f.input :origin, label: false, placeholder: "Moving from (enter City)" %>
							</div>
						</div>
						<div class="row">
							<div class="col-sm-12">
								<%= f.input :destination, label: false, placeholder: "Moving to (enter City)" %>
							</div>
						</div>	
						<div class="when-you-move">
							<div class="row">
								<div class="col-sm-12">
									<h3>When are you moving?</h3>
									<%= f.input :origin, label: false, placeholder: "My move date is" %>
									<p>Note : select an approximate date if you are unsure</p>

								</div>
							</div>
						</div>
					</div>
					<hr>
					<div class="row">
						<div class="next-button">
							<%= f.submit "Next", class: "btn btn-next"  %>
						</div>
					</div>
						
				</div>
				<div class="col-sm-6">
					<div class="flexbox">
						<div class="information-box">
							<%= image_tag "bulb.svg", height: 30, class: "lamp-icon" %>
							<p>86% of expats listing their container find at least 1 person to split costs with, within a week.</p>
						</div>
					</div>
				</div>
			<% end %>
		</div>	
	</div>

	<!-- container information -->

	<div class="container">
		<div class="row">
			<%= simple_form_for @container, url: containers_path do |f| %>
			  	<%#  f.input :venue_id, :as => :hidden, :input_html => { :value => @venue.id } %>
				<div class="col-sm-6">
					<div class="itinerary-section form">
						<div class="row">
							<div class="col-sm-12">
								<h3>What is the size of your container?</h3>
								<%= f.input :container_size, label: false, placeholder: "My container size" %>
							</div>
						</div>
						<div class="row">
							<div class="col-sm-8">
								<h3>What is the volume of your move?</h3>
								<%= f.input :volume, label: false, placeholder: "Enter your volume" %>
							</div>
							<div class="col-sm-4">
								<%= f.input :metrics, label: false,input_html: { class: 'input2-margin-top' }, collection: Container::METRIC, prompt: params[:metrics] %>
							</div>
						</div>	
						<div class="when-you-move">
							<div class="row">
								<div class="col-sm-8">
									<h3>How much are you paying for your move?</h3>
									<%= f.input :price, label: false, placeholder: "Enter amount here" %>

								</div>
								<div class="col-sm-4">
									<%= f.input :currency, label: false, input_html: { class: 'input2-margin-top' },  collection: Container::CURRENCIES, prompt: params[:currency]%>
								</div>
								<div class="row">
									<div class="col-sm-12">
										<div class="container-info">
											<p>Note : Enter the amount excluding insurance & other accessorial costs then choose the currency. <br>
										Entering the price of your move helps us suggest selling prices for the space you don’t use.</p>
										</div>
										
									</div>
								</div>	
							</div>
						</div>
					</div>
					<hr>
					<div class="row">
						<div class="next-button">
							<%= f.submit "Next", class: "btn btn-next"  %>
						</div>
					</div>
						
				</div>
				<div class="col-sm-6">
					<div class="flexbox">
						<div class="information-box">
							<%= image_tag "bulb.svg", height: 30, class: "lamp-icon" %>
							<p>2 expats are moving on a similar itinerary and looking for space.</p>
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>

<!-- mover information -->

	<div class="container">
		<div class="row">
			<%= simple_form_for [@container, @groupage], :html => { :multipart => true }, :url => {:controller => 'groupages', :action => 'create'} do |f| %>
					<div class="col-sm-6">
						<div class="itinerary-section form">
							<div class="row">
								<div class="col-sm-12">
									<h3>Which moving company have you selected to handle your move?</h3>
									<%= f.input :mover, label: false, placeholder: "Enter name of the moving company" %>
									<p>Note : We need to verify that we already have a partnership with your moving company. In case we don’t, we will reach out to add your mover to our list of approved partners.</p>
								</div>
						</div>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="flexbox">
							<div class="information-box">
								<%= image_tag "bulb.svg", height: 30, class: "lamp-icon" %>
									<p>Listing your container, we think you could earn up to <b>2,200</b> USD 
									 <button type="button" class="btn btn-information" data-toggle="modal" data-target="#estimate">
										  <i class="fas fa-info-circle"></i>
									</button>
								</p> 
								
							</div>
						</div>
					</div>
			<% end %>
			 <%= render 'containers/modal_information' %>
		</div>
	</div>

	<!-- notification information -->

	<div class="container">
		<div class="row">
			<%= simple_form_for [@container, @groupage], :html => { :multipart => true }, :url => {:controller => 'groupages', :action => 'create'} do |f| %>
				<div class="col-sm-6">
					<div class="itinerary-section form">
						<div class="row">
							<div class="col-sm-12">
								<h3>Where should we notify you when your container is live?</h3>
								<%= f.input :notification_email, label: "My main email address is", placeholder: "Email" %>
								<h4>Your email will never be shared with anyone.</h4>
							</div>
						</div>
						<div class="row">
							<div class="col-sm-2">
								<%= f.input :phone_prefix, label: false, collection: Groupage::PHONE_PREFIX, input_html: { class: 'input-margin-top' } , prompt: params[:phone] %>
							</div>
							<div class="col-sm-10">
								<%= f.input :notification_email, label: "Phone number (optional)", placeholder: "My phone number" %>
								<p> <span class="parapgraph-margin-left">In case we need further details on your move.</span></p>
							</div>
						</div>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="flexbox">
						<div class="information-box">
							<%= image_tag "bulb.svg", height: 30, class: "lamp-icon" %>
								<p>Listing your container, we think you could earn up to <b>2,200</b> USD 
								 <button type="button" class="btn btn-information" data-toggle="modal" data-target="#estimate">
									  <i class="fas fa-info-circle"></i>
								</button>
								</p> 
							
						</div>
					</div>
				</div>
			<% end %>
		</div>
	</div>

</div>

app/views/groupages/index.html.erb
<div class="full-wrapper-results">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-md-offset-2">
				<div class="row">
					<div class="col-xs-12">
						<div class="search-params-box hidden-xs">
							<p><%= @groupage[:origin]%> > <%= @groupage[:destination]  %></p>

							<p> <span class="departure_date"><%= Date.parse(@groupage[:departure_date]).strftime("%d %b %Y" ) unless params[:groupage][:departure_date].blank? %></span> </p>
						
						</div>
						<div class="search-params-box-mob hidden-sm hidden-md hidden-lg">
							<p><i class="fas fa-map-marker-alt"></i> <b>From:</b> &nbsp;<%= @groupage[:origin]%></p>
							<p><i class="fas fa-map-marker-alt"></i> <b>To:</b> &nbsp;<%= @groupage[:destination]%></p>

							<p><i class="far fa-calendar-alt"></i> <b>Date:</b> &nbsp;<span class="departure_date"><%= Date.parse(@groupage[:departure_date]).strftime("%d %b %Y" ) unless params[:groupage][:departure_date].blank? %></span> </p>
						
						</div>

					</div>
				</div>
				<div class="row">
					<div class="col-xs-5">
						<div class="lighthouse-img">							
						</div>
						
					</div>
					<div class="col-xs-7">
						<div class="alert-section">
							<h2>All containers are fully booked. <br> Create an alert and be notified when new containers are available!</h2>
							<div class="button-create-alert">
								<%#= link_to "Create alert", new_alert_path , class: "btn-create-alert" %>
								<%#= link_to "Create alert", params.slice(:sort).merge(per_page: 20), new_alert_path, class: "btn-create-alert"  %>
								<%= link_to "Create alert", new_alert_path( @params_hash), class: "btn-create-alert" %>
							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	
</div>

app/views/groupages/new.html.erb
<div class="full-container">
	<!-- itenerary section -->
	<div class="progressbar">
		
		<div class="logo">
			<%= link_to  new_container_path, class: "navbar-wagon-brand" do %>
      			<%= image_tag "balloons@3x.png", height: 50, class: "ballon-logo" %>
    		<% end %>
    		<h2>Step 1 : Start with the basics </h2>
		</div>	
	</div>
	<div class="progress">
  		<div class="progress-bar background-tuorquoise" role="progressbar" style="width: 50%" aria-valuenow="50" aria-valuemin="0" aria-valuemax="100">
  			
  		</div>
	</div>
	<div class="container">
		<div class="row">
			<%= simple_form_for [@container, @groupage], :url => {:controller => 'groupages', :action => 'create'} do |f| %>
			<%#  f.input :container_id, :as => :hidden, :input_html => { :value => @container.id } %>
				<div class="col-xs-12 col-sm-6">
					<div class="itinerary-section form">
						<div class="row">
							<div class="col-xs-12 col-sm-12">
								<h3>What is your move’s itinerary?</h3>
								<%= f.input :origin, label: false, placeholder: "Moving from (enter City)", input_html: { id: "origin-address" }%>
							</div>
						</div>
						<div class="row">
							<div class="col-xs-12 col-sm-12">
								<%= f.input :destination, label: false, placeholder: "Moving to (enter City)", input_html: { id: "destination-address" } %>
							</div>
						</div>	
						<div class="when-you-move">
							<div class="row">
								<div class="col-xs-12 col-sm-12">
									<h3>When are you moving?</h3>
									    <%= f.input :departure_date, as: :string, required: false, label: false, input_html: {class: "datepicker"}, placeholder: "My move date is" %>
									<p>Note : select an approximate date if you are unsure</p>

								</div>
							</div>
						</div>
						<hr class="hidden-xs">
						
						<div class="row hidden-xs">
							<div class="btn-section">
								<div class="back-link">
									<%#= link_to 'Back to this p', url_for(:back) %>
									<%= link_to containers_form_opening_path, class: "btn-back-link" do %>
											<i class="fas fa-chevron-left"></i>
										<% end %>
									<%= link_to "Back", containers_form_opening_path, class: "btn-back-link" %>
									
									
								</div>
								<div class="next-button">
									<%= f.submit "Next", class: "btn btn-next"  %>
								</div>
							</div>
						</div>
					</div>
					
						
				</div>
				<div class="col-xs-12 col-sm-6">
					<div class="flexbox">
						<div class="information-box">
							<%= image_tag "bulb.svg", height: 30, class: "lamp-icon" %>
							<p>86% of expats listing their container find at least 1 person to split costs with, within a week.</p>
						</div>
					</div>
				</div>
				<div class="hidden-sm hidden-md hidden-lg">
					<!-- <div class="col-xs-12"> -->
						<div class="action-buttons-section">
							<div class="back-link">
								<%#= link_to 'Back to this p', url_for(:back) %>
								<%= link_to containers_form_opening_path, class: "btn-back-link" do %>
										<i class="fas fa-chevron-left"></i>
									<% end %>
								<%= link_to "Back", containers_form_opening_path, class: "btn-back-link" %>
								
								
							</div>
							<div class="next-button">
								<%= f.submit "Next", class: "btn btn-next"  %>
							</div>
						</div>
					<!-- </div> -->
					
				</div>
			<% end %>
		</div>	
		

	</div>

</div>

app/views/groupages/show.html.erb
<h1>Groupages#show</h1>
<p>Find me in app/views/groupages/show.html.erb</p>